name: eii_backend
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - flask
  - flask-cors
  - werkzeug
  - geopandas
  - pip
  - reportlab
  - pip:
      - environmental-insights
      - python-dotenv
